### ISSUE TITLE
Add community links and Logos 

### ISSUE THREAD

**Issue by Theylon** [royosherove/afikoman#1]
Web3IL Telegram https://t.me/Web3Hebrew https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Telegram_logo.svg/640px-Telegram_logo.svg.png

WebeIL Discord https://discord.com/invite/JcDTX5eeM8 
https://toppng.com/uploads/preview/discord-logo-01-discord-logo-11562849833clsolz2mbc.png

Web3Dev discord https://discord.gg/BHhkqmUF
https://toppng.com/uploads/preview/discord-logo-01-discord-logo-11562849833clsolz2mbc.png

**Comment by royosherove** [comment]
Done
